#!/bin/zsh
# This hook is run after a new virtualenv is activated.
proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
mkdir $HOME/Development/Projects/$proj_name
add2virtualenv $HOME/Development/Projects/$proj_name
cd $HOME/Development/Projects/$proj_name
